### ISSUE TITLE
Semi modal view crashes if it has outlets 

### ISSUE THREAD

**Issue by raulrea** [kentnguyen/KNSemiModalViewController#1]
If the semi modal view controller has a nib file with outlets it will cash
If it has uibuttons, it crashes when tapping on them
If it is a view controller / table view delegate with a table view inside it, crash happens when the table view delegate methods are called by the controller

Xcode doesn't provide info on where it crashed
All it shows is EXC_BAD_ACCESS

**Comment by kentnguyen** [comment]
Fixed in f03b5041c3aec0f0e149c0c0c45a4157dc72e710
