### ISSUE TITLE
Using in Storyboard structure.

### ISSUE THREAD

**Issue by kevwkev** [kentnguyen/KNSemiModalViewController#12]
Hi Kent, 

Thanks for sharing your code. It's absolutely beautiful! In fact i think it looks better than what National Geographic has.
I have having some issues integrating it to my storyboard project. 
1. I am using QuickDialog to create a viewController, the view is being present from tab view controller.
- (IBAction)startReservation:(id)sender {
  QRootElement *root = [ReservationForm createSampleControls];
  UINavigationController *navigation = [QuickDialogController controllerWithNavigationForRoot:root];
  [self presentModalViewController:navigation animated:YES];
  }

I replaced [self presentModalViewController:navigation animated:YES]; with
[self presentSemiViewController:navigation];

The attampt was able to present the new  view with Semi Modal style, but when executing the dismiss action in the new view, the application will crash without giving a clear explanation of the error.

I guess i am asking here is if it's possible for you to provide an example of how to use your code in a storyboard project.

Thanks,
Kevin

**Comment by kentnguyen** [comment]
Hi Kevin,
Seems like you are new to Xcode debugging. You could find out exactly which line causes the crash by doing all these steps:
- Turn on "All Objective C" break point
- Turn on NSZombie
- Run on simulator, not device.

That should make the execution stop at the specific line.
