### ISSUE TITLE
Flip side view controller

### ISSUE THREAD

**Issue by ghost** [kentnguyen/KNSemiModalViewController#13]
I have been using the KNSemiViewController for a project and it is used in almost all the views. But, I am experiencing some serious problems now. 

I have a tableview and on selection of a cell, the semi modal view is presented but it does not finish there. There are few buttons which makes the semi view to flip horizontally. Since the view controller are retained, it works great with this flip view controller as well.

Now, this flip view also has some buttons and user interface elements which would present a modal view controller full sized but some serious trouble evolve when this new view controller is presented. The top portion of the view in the view controller always acts like a active part and so dismisses all the view controllers at once. And also if the UIToolbar is present with some buttons, I am not able to press the button and the view suddenly vanishes. This triggers the dismissSemiView somehow. 

How can this issue be corrected in KNSemiViewController.

Well, if you could also explain me some better ways to achieve such effect, it would be much helpful.

I will really appreciate your response and help.

**Comment by kentnguyen** [comment]
This is an usually complex UX that I don't recommend.

However, to remove "active part" you can remove this line in .m source file, around line 95

```
[dismissButton addTarget:self action:@selector(dismissSemiModalView) forControlEvents:UIControlEventTouchUpInside];
```

**Comment by ghost** [comment]
Well, I know this can be done by disabling the button. However is there a way to find the pointer to the button in current view controller. I tried but could not find one. If I could get a pointer to this, I will resolve the issue.

**Comment by kentnguyen** [comment]
I don't quite get what you mean. As I said, you have a strange use case which I don't recommend. If you need to find the reference to the close button, please look at the source code, you should be able to find the close button around the same line I mentioned.

**Comment by FredvanRijswijk** [comment]
How do you open a another view from the semiview? I tried to use storyboard, I tried to open it with code... Can you share me some code how you did that with your SemiView and flip to other view with buttons?
