### ISSUE TITLE
Landscape support

### ISSUE THREAD

**Issue by devfly** [kentnguyen/KNSemiModalViewController#14]
Are you going to implement a landscape support? I'm using this for my app, but I need to implement landscape support. Thank you!

**Comment by kentnguyen** [comment]
Presenting modal view in landscape mode probably not too hard, what's
difficult is handling the orientation changes.

**Comment by kentnguyen** [comment]
Partial landscape support is now possible in the latest code on master.

It can present landscape modal view but it won't handle orientation changes. You can try the demo and see the effect.

**Comment by sridvijay** [comment]
Looks great! Thanks for adding :)
