### ISSUE TITLE
How about a new release?

### ISSUE THREAD

**Issue by allenhuang** [kentnguyen/KNSemiModalViewController#20]
Hi

I love your work on this.

I installed it from Cocoapods. But the latest release (tag 0.1) seems too old.
Would you mind to update a more latest and stable version?

**Comment by kentnguyen** [comment]
thanks for reminding. i'm not a cocoapods user so didnt notice it.

**Comment by allenhuang** [comment]
Thanks. I also updated Cocoapods Spec already.
