### ISSUE TITLE
Buttons to open another view

### ISSUE THREAD

**Issue by FredvanRijswijk** [kentnguyen/KNSemiModalViewController#22]
I'm trying to finish a project, but I'm stuck on the buttons in a SemiView, I want to open another view with these buttons, I get crashes with any code I tried... Is it possible to open another view ? 

Anybody did this already? It will be great if some body can help me with this finishing piece! ;-)

**Comment by kentnguyen** [comment]
Please update to latest version of the code (today) and see if what you want to do is easier.

**Comment by FredvanRijswijk** [comment]
Oké, thanks I'm gone try that today! It's something like the National Geographic example... It will be helpfull for others I think to put it in your examples?

**Comment by kentnguyen** [comment]
I'm not exactly sure what you want to do, my examples are the basic one, it will fit most of the use cases if you look carefully.

**Comment by FredvanRijswijk** [comment]
Simple in the original image 1 "Explore on map" button opens another view, that's causing me zombie's, I love to have an example that use a button that's opening another view...

Like the resizeSemiModalView opens the KNAboutViewController?
