### ISSUE TITLE
Setting Frame at startup

### ISSUE THREAD

**Issue by uzman** [kentnguyen/KNSemiModalViewController#26]
hi,
is there any method for setting semimodalview's frame at startup?

i used standard objc code:
semiVC = [[KNThirdViewController alloc] initWithNibName:@"KNThirdViewController" bundle:nil];
semiVC.view.frame=CGRectMake(0, 50, 320, 410);

**Comment by kentnguyen** [comment]
I believe this is a basic implementation question. I do not provide support for this matters.
