### ISSUE TITLE
Shadow when orientation changes from portrait to landscape

### ISSUE THREAD

**Issue by kunalsood** [kentnguyen/KNSemiModalViewController#28]
It might be a good idea to resize the shadow when orientation changes. Currently, if SemiModal is presented in portrait & the device is rotated to landscape, the shadow remains 320 wide.

**Comment by mRs-** [comment]
That's the problem of SemiModal, it's not implemented yet to work in Landscape.

@kentnguyen wrote in the ToDo Section of his blog entry, that this is a known Bug. Maybe you can fix this Problem and hand in a pull request.

**Comment by mRs-** [comment]
Here is my fix: https://github.com/mRs-/KNSemiModalViewController

**Comment by kentnguyen** [comment]
@mrS- could you submit the pull request?

**Comment by mRs-** [comment]
did it
