### ISSUE TITLE
Rotation Animation Problems

### ISSUE THREAD

**Issue by mRs-** [kentnguyen/KNSemiModalViewController#32]
The Animation in a rotation is not really clean. If you have a UITabBar or / and a UINavigationBar and rotate the SemiModalView the TabBar and the NavigationBar is appearing during the rotation animation. After the rotation the screenshot is not showing the original state of the hidden background view.

**Comment by kentnguyen** [comment]
Yes I can see the flickering UITabbar appearing during the animation but not sure I can do much about that. 

I don't understand what you meant by the last part though. Please send screenshot.
