### ISSUE TITLE
`viewWillAppear:` not called on the presented ViewController

### ISSUE THREAD

**Issue by besi** [kentnguyen/KNSemiModalViewController#34]
I show a semi-modal `UIViewController` like so:

``` objc
self.datePickerVC = ...
[self presentSemiViewController:self.datePickerVC withOptions:nil];
```

Now In my `datePickerVC` I assume that `viewWillAppear:` is called, before my ViewController is presented. This does not seem to be done by KNSemiModalViewController.

**Comment by besi** [comment]
Currently I can work around the issue by using nonatomic setters or by calling the method myself.

**Comment by kentnguyen** [comment]
Which OS version are you running on?

**Comment by besi** [comment]
It's 6.0 but supporting iOS 5.0

Am 28/02/2013 um 13:08 schrieb Kent Nguyen notifications@github.com:

**Comment by kentnguyen** [comment]
I cannot reproduce the bug. Adding these to `KNThirdViewController.m` and set a break point, you will see it breaks as expected for both iOS 5 & 6

```
-(void)viewWillAppear:(BOOL)animated {
  [super viewWillAppear:animated];
  NSLog(@"DO Something");
}
```
