### ISSUE TITLE
Weird color appears on UIButton in Parent View Controller

### ISSUE THREAD

**Issue by thkeen** [kentnguyen/KNSemiModalViewController#36]
![iOS Simulator Screen shot Mar 18 2013 3 44 06 PM](https://f.cloud.github.com/assets/900629/269706/3b1bb708-8fa8-11e2-8ab3-a3667312f86b.png)

You can notice on the UIButton in the Parent View Controller in the back ("Load earlier messages"), after being presented, there is a straight line of few colors appeared on that UIButton. I'm not sure why does this happen? Am I expected to do something to avoid this?

Thanks a lot!

**Comment by kentnguyen** [comment]
Not sure why. Try adding a delay of 0.1second, before presenting the modal

**Comment by kentnguyen** [comment]
It seems like it appears only on Rounded Rect button and nothing else.

Won't fix.
