### ISSUE TITLE
Performance of MapView in SemiModalViewController is poor

### ISSUE THREAD

**Issue by thkeen** [kentnguyen/KNSemiModalViewController#37]
When I put a mapView inside the SemiModal View Controller, its performance is very poor when I tried to pinch/zoom/navigate through the mapView. What is the reason behind this?

**Comment by kentnguyen** [comment]
I have confirmed the bug. It seems to be conflicting with the shadow of the semimodal. If you remove the 4 lines of shadow code around line 242 in .m file, the performance will not be affected.

This is beyond my knowledge, however.

**Comment by thkeen** [comment]
Confirmed that above fix works. However it doesn't look nice as before. I will figure another way to display the shadow though! :) Thank you very much.
