### ISSUE TITLE
Error while try to run sample project

### ISSUE THREAD

**Issue by AalokParikh** [kentnguyen/KNSemiModalViewController#38]
> KNSemiModalViewController->master/KNSemiModalViewControllerDemo/KNThirdViewController.m:50:32: No visible @interface for 'UIView' declares the selector 'containingViewController'
> 
> KNSemiModalViewController->master/KNSemiModalViewControllerDemo/KNThirdViewController.m:42:32: No visible @interface for 'UIView' declares the selector 'containingViewController'

These two errors are shown when ever I try to build the project.

![Screen Shot 2013-03-21 at 11 42 07 AM](https://f.cloud.github.com/assets/1628260/284542/c43b0c26-91ee-11e2-8b6e-034a3d9ffce9.png)

![Screen Shot 2013-03-21 at 11 41 51 AM](https://f.cloud.github.com/assets/1628260/284547/d46993e2-91ee-11e2-9cd4-9fdd4afb0b77.png)

**Comment by kentnguyen** [comment]
Which xcode version are you using?

**Comment by AalokParikh** [comment]
![Screen Shot 2013-03-21 at 3 14 53 PM](https://f.cloud.github.com/assets/1628260/285041/078e3d78-920c-11e2-9597-7f5ccb7055a9.png)

This one :100:

**Comment by kentnguyen** [comment]
Fixed in commit https://github.com/kentnguyen/KNSemiModalViewController/commit/4ba644b1846d1399601f3fcbf48818be041ac552

Please download source code directly

**Comment by AalokParikh** [comment]
Thanks for providing your valuable time to help me out.

**Comment by shmidt** [comment]
I have the same error messages after I copied KNThirdViewController.m to my project.
What causing this error message to appear?

Upd.: there is outdated version of the repo at CocoaPods.

**Comment by smuralikrish** [comment]
I have the same error ,i am using Xcode 6.3.2.
