### ISSUE TITLE
The view animation is now working, if using with IIViewDeckController.

### ISSUE THREAD

**Issue by krazie99** [kentnguyen/KNSemiModalViewController#39]
There's no crash but, when call the method "presentSemiViewController", the slide up animation not working. It looks like "presentModalView animated:NO". 
I can't solve the problem. 

IIViewDeckController + KNSemiModalViewController.

**Comment by kentnguyen** [comment]
Have you checked the other questions?

**Comment by krazie99** [comment]
Already, I checked. but, I have no idead ;=(

This is what happen to me : http://youtu.be/3NmBH3OTI8E

**Comment by kentnguyen** [comment]
If you can send me the entire code maybe I can help. The problem with other libraries are difficult to determine.

**Comment by kentnguyen** [comment]
You can zip and give a link to that file here.

**Comment by krazie99** [comment]
Here is Download : https://www.dropbox.com/s/wo7hnlplug1kcut/Coloris.zip
Thank you so much.

**Comment by kentnguyen** [comment]
Why are you not using ARC?

**Comment by kentnguyen** [comment]
You have a very bad code structure. There is nothing wrong with KNSemiModal.

```
// [self presentSemiViewController:navController];
[self presentSemiViewController:[[UIViewController alloc] init]];
```

I did a "control" test and it is working fine.

# 

NOTE TO OTHERS: Do NOT ask for support for IIViewDeckController anymore. There is nothing wrong with it and my library. It is your code!

**Comment by lanceylai** [comment]
I have been solved this problem.
please use window.rootViewController, not self to call  presentSemiViewController....
this is my code , hope it will hepl you.

```
[[AppDelegate sharedAppDelegate].window.rootViewController presentSemiViewController:shareViewController withOptions:@{
                                                         KNSemiModalOptionKeys.pushParentBack    : @(YES),
                                                         KNSemiModalOptionKeys.animationDuration : @(0.3),
                                                         KNSemiModalOptionKeys.shadowOpacity     : @(0.3),
                                                         KNSemiModalOptionKeys.parentScale       : @(0.95),
                                                         }];
```

this is dismiss:

```
  if ([[AppDelegate sharedAppDelegate].window.rootViewController respondsToSelector:@selector(dismissSemiModalView)]) {
    [[AppDelegate sharedAppDelegate].window.rootViewController dismissSemiModalView];
  }

```
