### ISSUE TITLE
Error after added UIViewController+KNSemiModal.h

### ISSUE THREAD

**Issue by DivideK** [kentnguyen/KNSemiModalViewController#46]
Hello,

First of all, thank you for this work. It looks great.

But, I have an error (6 in fact) when I add your module.

I have a "Use undeclared identifier 'KNSKNSemiModalTransitionStyleSlideUp'...".
It's the same error for each transition style in the .h line 46 to 50.

Looking forward to an answer, thank you in advance.

PS: it's ok on iOS 6 but not in 5 and the demo as the same problem.

**Comment by kentnguyen** [comment]
Please try latest commit from here and let me know
