### ISSUE TITLE
Present semi-modal view from left or right side of window

### ISSUE THREAD

**Issue by ilant** [kentnguyen/KNSemiModalViewController#47]
It would be nice to add functionality for presenting the semi-modal view from left or right side - with pushed background animation !

Thanks, 
Ilias

**Comment by jlubeck** [comment]
And from the top as well!

**Comment by kentnguyen** [comment]
Sorry, I would not support this feature in this library. Partially explained here: https://github.com/kentnguyen/KNSemiModalViewController/issues/40

It would be a different kind of 'feel' together for the library. I'd prefer to keep it strictly "modal" from bottom to top
