### ISSUE TITLE
UINavigationController Inside SemiView

### ISSUE THREAD

**Issue by MrMaksimize** [kentnguyen/KNSemiModalViewController#52]
I might just be stupid :)  

But I'm wondering - is it possible at all to put a navigation controller inside the semimodal?

When I try to do this, the navigation controller just ignores it, and fills the full screen.

Thanks!

**Comment by mixdesign** [comment]
Anybody will answer to this good question??

**Comment by mvalti** [comment]
Just set the navigationcontroller frame to any position:

```
UIViewController *controller = [UIViewController alloc]init];
UINavigationController *navControlller= [[UINavigationController alloc] initWithRootViewController:controller];
self.navControlller.view.frame = CGRectMake(0.0, 100.0, 320.0, 480.0 - 100.0);
[self presentSemiViewController:self.navControlller withOptions:@{
 KNSemiModalOptionKeys.pushParentBack : @(YES),
 KNSemiModalOptionKeys.shadowOpacity : @(0.3)
 }
```

**Comment by kentnguyen** [comment]
@mvalti suggested correctly. However you might want to reconsider your design/use case. Having UINavigationController inside the modal will lead to several problems later. You might be better off using a simple scrollview?
