### ISSUE TITLE
UISegmentedControl current selected element text disappears

### ISSUE THREAD

**Issue by SabatinoMasala** [kentnguyen/KNSemiModalViewController#61]
When you have a UISegmentedControl on the screen and you open up a semi view, the text of the current selected element disappears.
![screen shot 2014-04-04 at 01 17 23](https://cloud.githubusercontent.com/assets/2678345/2610390/25610e44-bb86-11e3-8b23-ebf56e8d8e49.png)
![screen shot 2014-04-04 at 01 17 25](https://cloud.githubusercontent.com/assets/2678345/2610391/25610e62-bb86-11e3-870f-e72a33253adc.png)

**Comment by dchohfi** [comment]
+1 on this

**Comment by dchohfi** [comment]
@SabatinoMasala could you check if this still happening for you? If not would you mind to close the issue?

**Comment by SabatinoMasala** [comment]
It's okay now, awesome!
