### ISSUE TITLE
when i call presentSemiView on iphone6 or iphone6 plus,The sceen will flash

### ISSUE THREAD

**Issue by super-chen** [kentnguyen/KNSemiModalViewController#69]

**Comment by thomasdegry** [comment]
Same behavior in the demo application, when I use the classes in mine the issues doesn't seem to happen though. I feel it has something to do with weird scaling in the demo application, the demo app's status bar is also sized bigger than other apps.

**Comment by wy19901227** [comment]
是得，所以请问 还有类似的这个的第三方类吗？

**Comment by yuzhongxingke** [comment]
请问有人解决这个问题啦吗？求指教呀，好像在5s 上是好的，就是6以上的不行，好像是尺寸的问题

**Comment by yuzhongxingke** [comment]
找到问题原因啦，[target drawViewHierarchyInRect:target.bounds afterScreenUpdates:YES];这句话造成的，改为 NO 就可以啦

**Comment by jerroy** [comment]
> 找到问题原因啦，[target drawViewHierarchyInRect:target.bounds afterScreenUpdates:YES];这句话造成的，改为 NO 就可以啦

会产生其他问题~

**Comment by jerroy** [comment]
kn_interfaceOrientationDidChange 把这个收到通知里面的代码注释了就行，试了下，暂时没什么影响
