### ISSUE TITLE
Push to the next ViewController, overlapping images, fuzzy, pop back also can appear

### ISSUE THREAD

**Issue by yimouleng** [kentnguyen/KNSemiModalViewController#80]
I in the ViewController present a ViewController menu, click on the menu button, push on to the next ViewController, pictures will be overlapping, fuzzy.
The following is a part of the code：

```
PopBlackViewController * PopBlackView = [PopBlackViewController new];
    NSArray * arr = @[@"hello",@"push"];
    [PopBlackView showBlackView:@"123" titleArr:arr];
    PopBlackView.popViewBlock =^(NSInteger num){
        if (num == 0)
        {
            NSLog(@"1");
        }else
        {
            [self.navigationController pushViewController:[SendInvitationViewController new] animated:YES];
        }
    };

[self presentSemiViewController:PopBlackView withOptions:@{
                                                                            KNSemiModalOptionKeys.pushParentBack    : @(NO),
                                                                            KNSemiModalOptionKeys.animationDuration : @(0.6),
                                                                            KNSemiModalOptionKeys.shadowOpacity     : @(0.3),
                                                                            }];
```

Push to the next ViewController, overlapping images, fuzzy, pop back also can appear

**Comment by DeftMKJ** [comment]
me too！！when i push ，tha NavigationBar was disappear ！！？？what's wrong？
my code was same with above.pls help me！！

**Comment by DeftMKJ** [comment]
yeah，my problem sovled ！！！try this in the callback Block
        [weakSelf.chooseVC.view removeFromSuperview];
        [weakSelf.chooseVC removeFromParentViewController];
        weakSelf.chooseVC.view = nil;
        weakSelf.chooseVC = nil;

**Comment by yimouleng** [comment]
I look at the source code, is used in screenshots, you speak this way at the back of the parameters, a jump will not be torn。

[self presentSemiViewController:PopBlackView withOptions:@{
                                                                            KNSemiModalOptionKeys.pushParentBack    : @(NO)
                                                                            }];
